version: '3.8'

services:

  ts-api-docker:

    build:
      context: .
      dockerfile: Dockerfile

    deploy:
      replicas: 4

    restart: always

    environment:
      - PING_LISTEN_PORT=3000
    volumes:
      - ./:/usr/src/app
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ts-api-docker